import { Company, PlacementDrive, Question, UserProfile, Application, QuizAttempt, MockInterviewRecord } from '../types';

export const INITIAL_STUDENTS: UserProfile[] = [
  {
    id: 's101',
    full_name: 'Alex Turner',
    email: 'alex.turner@campus.edu',
    phone: '+91 98765 43210',
    department: 'Computer Science & Engineering',
    year: 'Final Year (2025)',
    register_number: '21CS042',
    skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Data Structures', 'Tailwind CSS'],
    resume_url: 'https://example.com/resumes/alex-turner.pdf',
    avatar_url: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&h=150&fit=crop&crop=faces',
    role: 'student',
    cgpa: 8.85,
    created_at: '2024-08-01T10:00:00Z',
  },
  {
    id: 's102',
    full_name: 'Priya Sharma',
    email: 'priya.sharma@campus.edu',
    phone: '+91 98765 12345',
    department: 'Information Technology',
    year: 'Final Year (2025)',
    register_number: '21IT019',
    skills: ['Python', 'Machine Learning', 'SQL', 'FastAPI', 'Pandas'],
    resume_url: 'https://example.com/resumes/priya-sharma.pdf',
    avatar_url: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&h=150&fit=crop&crop=faces',
    role: 'student',
    cgpa: 9.12,
    created_at: '2024-08-02T11:00:00Z',
  },
  {
    id: 's103',
    full_name: 'Rahul Varma',
    email: 'rahul.v@campus.edu',
    phone: '+91 98111 22334',
    department: 'Electronics & Communication',
    year: 'Final Year (2025)',
    register_number: '21EC088',
    skills: ['C++', 'Embedded C', 'IoT', 'System Design'],
    resume_url: 'https://example.com/resumes/rahul-varma.pdf',
    avatar_url: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?w=150&h=150&fit=crop&crop=faces',
    role: 'student',
    cgpa: 7.45,
    created_at: '2024-08-05T09:30:00Z',
  }
];

export const INITIAL_STAFF: UserProfile = {
  id: 'staff01',
  full_name: 'Dr. Ronald Harris',
  email: 'dean.placement@campus.edu',
  phone: '+91 99000 88776',
  department: 'Dean of Training & Placement',
  year: 'Faculty',
  register_number: 'FAC-TPO-01',
  skills: ['Campus Recruitment', 'Corporate Relations', 'Skill Assessment', 'Talent Acquisition'],
  avatar_url: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&h=150&fit=crop&crop=faces',
  role: 'staff',
  created_at: '2023-01-01T00:00:00Z',
};

export const INITIAL_COMPANIES: Company[] = [
  {
    id: 'c1',
    name: 'Google',
    logo_url: 'https://images.unsplash.com/photo-1573804633927-bfcbcd909acd?w=120&h=120&fit=crop',
    description: 'Pioneering global technology, cloud software, distributed systems, and cutting-edge artificial intelligence.',
    website: 'https://careers.google.com',
  },
  {
    id: 'c2',
    name: 'Microsoft',
    logo_url: 'https://images.unsplash.com/photo-1642132652075-2bfa3f80c611?w=120&h=120&fit=crop',
    description: 'Empowering individuals and institutions with Azure cloud services, productivity suites, and enterprise engineering.',
    website: 'https://careers.microsoft.com',
  },
  {
    id: 'c3',
    name: 'Amazon',
    logo_url: 'https://images.unsplash.com/photo-1523474253246-6ef765507727?w=120&h=120&fit=crop',
    description: 'World leader in e-commerce marketplace and AWS cloud computing infrastructure.',
    website: 'https://amazon.jobs',
  },
  {
    id: 'c4',
    name: 'TCS Digital',
    logo_url: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=120&h=120&fit=crop',
    description: 'Premier digital innovation division delivering enterprise transformation and full-stack software development.',
    website: 'https://tcs.com/careers',
  },
  {
    id: 'c5',
    name: 'Deloitte USI',
    logo_url: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=120&h=120&fit=crop',
    description: 'Multinational professional services firm providing strategic tech advisory and cloud modernization solutions.',
    website: 'https://deloitte.com/careers',
  }
];

export const INITIAL_DRIVES: PlacementDrive[] = [
  {
    id: 'd1',
    company_id: 'c1',
    job_role: 'Associate Software Engineer',
    description: 'Develop high-scale backend services, optimize low-latency databases, and work on modern web architectures.',
    package: '24.5 LPA',
    location: 'Bengaluru / Hyderabad',
    eligibility: 'Min 8.0 CGPA | CSE, IT, ECE | 0 Active Backlogs',
    min_cgpa: 8.0,
    deadline: '2026-10-15T23:59:59Z',
    drive_date: '2026-10-22T09:00:00Z',
    created_at: '2026-09-15T10:00:00Z',
  },
  {
    id: 'd2',
    company_id: 'c2',
    job_role: 'Cloud Solution Engineer',
    description: 'Collaborate directly with global clients to architect and deploy highly available enterprise applications on Azure.',
    package: '18.0 LPA',
    location: 'Hyderabad / Noida',
    eligibility: 'Min 7.5 CGPA | All B.Tech Branches | Max 1 cleared backlog',
    min_cgpa: 7.5,
    deadline: '2026-10-18T23:59:59Z',
    drive_date: '2026-10-28T09:30:00Z',
    created_at: '2026-09-16T12:00:00Z',
  },
  {
    id: 'd3',
    company_id: 'c3',
    job_role: 'Graduate SDE (AWS)',
    description: 'Build mission-critical distributed services, real-time metrics pipelines, and developer tooling for AWS.',
    package: '22.0 LPA',
    location: 'Bengaluru',
    eligibility: 'Min 7.8 CGPA | CSE & IT | No backlogs',
    min_cgpa: 7.8,
    deadline: '2026-10-10T23:59:59Z',
    drive_date: '2026-10-16T09:00:00Z',
    created_at: '2026-09-10T08:00:00Z',
  },
  {
    id: 'd4',
    company_id: 'c4',
    job_role: 'Systems Engineer (Digital)',
    description: 'Build responsive web, mobile, and cloud solutions using React, Node.js, Spring Boot, and Docker.',
    package: '7.5 LPA',
    location: 'Chennai / Pune / Pan-India',
    eligibility: 'Min 6.5 CGPA | All Engineering Branches',
    min_cgpa: 6.5,
    deadline: '2026-10-30T23:59:59Z',
    drive_date: '2026-11-08T10:00:00Z',
    created_at: '2026-09-18T14:00:00Z',
  },
  {
    id: 'd5',
    company_id: 'c5',
    job_role: 'Technology Analyst - Cloud & Advisory',
    description: 'Drive digital transformation roadmaps, enterprise security assessments, and cloud migration frameworks.',
    package: '9.0 LPA',
    location: 'Gurugram / Hyderabad',
    eligibility: 'Min 7.0 CGPA | CSE, IT, ECE, EEE',
    min_cgpa: 7.0,
    deadline: '2026-11-05T23:59:59Z',
    drive_date: '2026-11-15T09:00:00Z',
    created_at: '2026-09-20T10:00:00Z',
  }
];

export const INITIAL_QUESTIONS: Question[] = [
  // --- QUANTITATIVE APTITUDE ---
  {
    id: 'q-apt-1',
    category: 'aptitude',
    topic: 'Percentages',
    question: 'A fruit seller had some apples. He sells 40% of the apples and still has 420 apples left. Originally, how many apples did he have?',
    option_a: '588',
    option_b: '600',
    option_c: '672',
    option_d: '700',
    correct_answer: 'D',
    explanation: 'Remaining apples = 100% - 40% = 60%. If 60% of X = 420, then X = (420 * 100) / 60 = 700.',
    difficulty: 'Easy',
    company: 'TCS Digital',
  },
  {
    id: 'q-apt-2',
    category: 'aptitude',
    topic: 'Profit & Loss',
    question: 'A shopkeeper sells a notebook at Rs. 180 gaining 20% on the cost price. What was the cost price of the notebook?',
    option_a: 'Rs. 140',
    option_b: 'Rs. 150',
    option_c: 'Rs. 160',
    option_d: 'Rs. 165',
    correct_answer: 'B',
    explanation: 'Selling Price = CP * 1.20 => 180 = 1.20 * CP => CP = 180 / 1.2 = Rs. 150.',
    difficulty: 'Easy',
    company: 'Deloitte',
  },
  {
    id: 'q-apt-3',
    category: 'aptitude',
    topic: 'Time & Work',
    question: 'A can do a piece of work in 15 days and B in 20 days. If they work on it together for 4 days, what fraction of work is left?',
    option_a: '7/15',
    option_b: '8/15',
    option_c: '1/3',
    option_d: '11/15',
    correct_answer: 'B',
    explanation: '1 day work of (A + B) = (1/15 + 1/20) = 7/60. Work done in 4 days = 4 * (7/60) = 7/15. Fraction of work left = 1 - 7/15 = 8/15.',
    difficulty: 'Medium',
    company: 'Amazon',
  },
  {
    id: 'q-apt-4',
    category: 'aptitude',
    topic: 'Time & Distance',
    question: 'A train 125 meters long passes a telegraph pole in 5 seconds. What is the speed of the train in km/h?',
    option_a: '70 km/h',
    option_b: '80 km/h',
    option_c: '90 km/h',
    option_d: '100 km/h',
    correct_answer: 'C',
    explanation: 'Speed = Distance / Time = 125m / 5s = 25 m/s. In km/h: 25 * (18 / 5) = 90 km/h.',
    difficulty: 'Medium',
    company: 'Google',
  },
  {
    id: 'q-apt-5',
    category: 'aptitude',
    topic: 'Ratio',
    question: 'Two numbers are in the ratio 3 : 5. If 9 is subtracted from each, the new numbers are in the ratio 12 : 23. The smaller number is:',
    option_a: '27',
    option_b: '33',
    option_c: '49',
    option_d: '55',
    correct_answer: 'B',
    explanation: 'Let numbers be 3x and 5x. (3x - 9) / (5x - 9) = 12 / 23. Cross multiply: 69x - 207 = 60x - 108 => 9x = 99 => x = 11. Smaller number = 3 * 11 = 33.',
    difficulty: 'Hard',
    company: 'Microsoft',
  },
  {
    id: 'q-apt-6',
    category: 'aptitude',
    topic: 'Average',
    question: 'The average of 5 consecutive odd numbers is 61. What is the difference between the highest and lowest numbers?',
    option_a: '4',
    option_b: '8',
    option_c: '10',
    option_d: '12',
    correct_answer: 'B',
    explanation: 'The numbers are 57, 59, 61, 63, 65. Highest = 65, lowest = 57. Difference = 65 - 57 = 8.',
    difficulty: 'Easy',
    company: 'TCS Digital',
  },

  // --- TECHNICAL PRACTICE ---
  {
    id: 'q-tech-1',
    category: 'technical',
    topic: 'Data Structures',
    question: 'Which of the following data structures is most efficient for implementing a Least Recently Used (LRU) Cache?',
    option_a: 'Stack and Array',
    option_b: 'Queue and Binary Search Tree',
    option_c: 'Doubly Linked List and Hash Map',
    option_d: 'Min-Heap and Binary Tree',
    correct_answer: 'C',
    explanation: 'A Hash Map provides O(1) key lookup, while a Doubly Linked List allows O(1) removal and node insertion at the head for recency tracking.',
    difficulty: 'Medium',
    company: 'Google',
    job_role: 'Software Engineer',
  },
  {
    id: 'q-tech-2',
    category: 'technical',
    topic: 'DBMS',
    question: 'In database management, which property guarantees that concurrent transactions execute without interfering with each other?',
    option_a: 'Atomicity',
    option_b: 'Consistency',
    option_c: 'Isolation',
    option_d: 'Durability',
    correct_answer: 'C',
    explanation: 'Isolation ensures that the execution of concurrent transactions yields the same state that would be obtained if they were executed sequentially.',
    difficulty: 'Easy',
    company: 'Amazon',
    job_role: 'SDE',
  },
  {
    id: 'q-tech-3',
    category: 'technical',
    topic: 'Operating Systems',
    question: 'What is "Thrashing" in an operating system?',
    option_a: 'High CPU utilization by background services',
    option_b: 'Excessive paging where the OS spends more time swapping pages than executing instructions',
    option_c: 'Corrupted disk sectors due to power outages',
    option_d: 'Deadlock between multiple worker threads',
    correct_answer: 'B',
    explanation: 'Thrashing occurs when the system does not have enough physical memory to hold the working sets of active processes, causing non-stop page faults.',
    difficulty: 'Medium',
    company: 'Microsoft',
    job_role: 'Cloud Architect',
  },
  {
    id: 'q-tech-4',
    category: 'technical',
    topic: 'OOP',
    question: 'Which OOP principle states that objects of a superclass should be replaceable with objects of its subclasses without breaking application behavior?',
    option_a: 'Open/Closed Principle',
    option_b: 'Liskov Substitution Principle (LSP)',
    option_c: 'Single Responsibility Principle',
    option_d: 'Interface Segregation Principle',
    correct_answer: 'B',
    explanation: 'LSP (the L in SOLID) guarantees that a derived class preserves the contracts and invariants of the base class.',
    difficulty: 'Medium',
    company: 'Google',
  },
  {
    id: 'q-tech-5',
    category: 'technical',
    topic: 'Computer Networks',
    question: 'During a TCP 3-way handshake, what is the sequence of flags exchanged between client and server?',
    option_a: 'SYN -> SYN-ACK -> ACK',
    option_b: 'ACK -> SYN -> SYN-ACK',
    option_c: 'SYN -> ACK -> FIN',
    option_d: 'RST -> SYN -> ACK',
    correct_answer: 'A',
    explanation: 'Client sends SYN, Server responds with SYN-ACK, and Client completes connection with ACK.',
    difficulty: 'Easy',
    company: 'Deloitte',
  },
  {
    id: 'q-tech-6',
    category: 'technical',
    topic: 'React',
    question: 'In React, why should state variables never be mutated directly (e.g. `state.user = "Bob"`)?',
    option_a: 'Because JavaScript throws a strict mode syntax error',
    option_b: 'Because React relies on reference equality to trigger re-renders and shallow comparisons',
    option_c: 'Because mutating state freezes the DOM thread',
    option_d: 'Because React converts all states to immutable byte arrays',
    correct_answer: 'B',
    explanation: 'React compares previous and next states by shallow reference. Direct mutation keeps the same object pointer, preventing re-render detection.',
    difficulty: 'Easy',
    company: 'TCS Digital',
  },

  // --- CRITICAL THINKING ---
  {
    id: 'q-crit-1',
    category: 'critical',
    topic: 'Logical Reasoning',
    question: 'Look at this series: 7, 10, 8, 11, 9, 12, ... What number should come next?',
    option_a: '7',
    option_b: '10',
    option_c: '12',
    option_d: '13',
    correct_answer: 'B',
    explanation: 'It is an alternating addition and subtraction series: +3, -2, +3, -2, +3, -2. 12 - 2 = 10.',
    difficulty: 'Easy',
    company: 'TCS Digital',
  },
  {
    id: 'q-crit-2',
    category: 'critical',
    topic: 'Syllogisms',
    question: 'Statements:\n1. All mangoes are golden.\n2. No golden things are cheap.\nConclusions:\nI. All mangoes are cheap.\nII. Golden mangoes are not cheap.',
    option_a: 'Only conclusion I follows',
    option_b: 'Only conclusion II follows',
    option_c: 'Either I or II follows',
    option_d: 'Neither I nor II follows',
    correct_answer: 'B',
    explanation: 'Since all mangoes are golden and no golden things are cheap, no mangoes are cheap. Therefore, golden mangoes are certainly not cheap.',
    difficulty: 'Medium',
    company: 'Deloitte',
  },
  {
    id: 'q-crit-3',
    category: 'critical',
    topic: 'Data Sufficiency',
    question: 'Is integer X even?\nStatement 1: 3X is an even integer.\nStatement 2: X/2 is an integer.',
    option_a: 'Statement 1 alone is sufficient',
    option_b: 'Statement 2 alone is sufficient',
    option_c: 'Both statements together are needed',
    option_d: 'Either statement alone is sufficient',
    correct_answer: 'D',
    explanation: 'From St. 1: 3 * odd is odd, so 3X even implies X is even. From St. 2: X/2 is integer implies X is divisible by 2, so X is even. Either statement alone is sufficient.',
    difficulty: 'Medium',
    company: 'Amazon',
  },
  {
    id: 'q-crit-4',
    category: 'critical',
    topic: 'Puzzles',
    question: 'Four friends (A, B, C, D) run a race. A finishes ahead of B but behind C. D finishes ahead of C. Who won the race?',
    option_a: 'A',
    option_b: 'B',
    option_c: 'C',
    option_d: 'D',
    correct_answer: 'D',
    explanation: 'Order: D > C > A > B. D finished first and won the race.',
    difficulty: 'Easy',
    company: 'Microsoft',
  },

  // --- INTERVIEW PREPARATION ---
  {
    id: 'q-int-1',
    category: 'interview',
    topic: 'HR Questions',
    question: 'Tell me about yourself and summarize your journey into software engineering.',
    correct_answer: 'Use the Present-Past-Future model: (1) Current college, major, primary tech stack; (2) Key capstone project/internship; (3) Why you are passionate about this specific company and role.',
    difficulty: 'Easy',
    company: 'Google',
    job_role: 'Software Engineer',
  },
  {
    id: 'q-int-2',
    category: 'interview',
    topic: 'Behavioral Questions',
    question: 'Describe a situation where a team project ran into conflict or missed a milestone. How did you handle it?',
    correct_answer: 'Employ the STAR framework (Situation, Task, Action, Result). Emphasize transparent communication, objective trade-offs, collaborative issue triage, and constructive outcome.',
    difficulty: 'Medium',
    company: 'Amazon',
    job_role: 'SDE',
  },
  {
    id: 'q-int-3',
    category: 'interview',
    topic: 'Technical Questions',
    question: 'How do you design a scalable URL shortener service (like bit.ly)? What components would you choose?',
    correct_answer: 'Address API design (encode/decode), Base62 hashing algorithm, Key-Value database (NoSQL/Redis cache for high read throughput), collision resolution, and distributed ID generators.',
    difficulty: 'Hard',
    company: 'Microsoft',
    job_role: 'Cloud Architect',
  },
  {
    id: 'q-int-4',
    category: 'interview',
    topic: 'Role-Based Questions',
    question: 'What happens behind the scenes from the moment you type google.com into your browser and press Enter?',
    correct_answer: 'Explain: DNS resolution (Browser cache -> OS -> Recursive resolver), TCP 3-way handshake, TLS negotiation, HTTP request dispatch, Server processing, DOM parsing, CSSOM construction, and Painting.',
    difficulty: 'Medium',
    company: 'Google',
    job_role: 'Associate Software Engineer',
  }
];

export const INITIAL_APPLICATIONS: Application[] = [
  {
    id: 'app-01',
    student_id: 's101',
    drive_id: 'd1',
    status: 'Shortlisted',
    applied_at: '2026-09-17T14:32:00Z',
  },
  {
    id: 'app-02',
    student_id: 's101',
    drive_id: 'd2',
    status: 'Applied',
    applied_at: '2026-09-18T09:15:00Z',
  },
  {
    id: 'app-03',
    student_id: 's102',
    drive_id: 'd1',
    status: 'Interview',
    applied_at: '2026-09-16T11:20:00Z',
  },
  {
    id: 'app-04',
    student_id: 's103',
    drive_id: 'd4',
    status: 'Selected',
    applied_at: '2026-09-12T16:45:00Z',
  }
];

export const INITIAL_QUIZ_ATTEMPTS: QuizAttempt[] = [
  {
    id: 'attempt-01',
    student_id: 's101',
    category: 'aptitude',
    topic: 'Percentages & Profit',
    score: 8,
    total_questions: 10,
    percentage: 80.0,
    completed_at: '2026-09-22T15:30:00Z',
  },
  {
    id: 'attempt-02',
    student_id: 's101',
    category: 'technical',
    topic: 'Data Structures & DBMS',
    score: 9,
    total_questions: 10,
    percentage: 90.0,
    completed_at: '2026-09-23T11:00:00Z',
  },
  {
    id: 'attempt-03',
    student_id: 's101',
    category: 'critical',
    topic: 'Logical Reasoning',
    score: 7,
    total_questions: 10,
    percentage: 70.0,
    completed_at: '2026-09-24T09:45:00Z',
  }
];

export const INITIAL_MOCK_INTERVIEWS: MockInterviewRecord[] = [
  {
    id: 'mock-01',
    student_id: 's101',
    job_role: 'Associate Software Engineer',
    score: 85,
    feedback: 'Excellent structural clarity when answering distributed system fundamentals. Suggested improvement: elaborate on edge cases in database concurrency.',
    completed_at: '2026-09-21T16:20:00Z',
  }
];
